# demo pod - https://docs.docker.com/get-started/orchestration/
# kubectl apply -f pod.yaml
# kubectl get pods
# kubectl logs demo
# kubectl delete -f pod.yaml

apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - name: testpod
    image: alpine:3.5
    command: ["ping", "8.8.8.8"]