name: ACR # Azure Container Registry

# Trigger workflow on push to master in containers folder
on:
  push:
    branches:
      - master
    paths:
      - "containers/**"

jobs:
  build:
    runs-on: ubuntu-latest

    # Get those containers into ACR
    steps:
      - uses: actions/checkout@v2

      - name: Log into Azure
        run: az login --service-principal
          --username ${{ secrets.service_principal }}
          --password ${{ secrets.service_principal_password }}
          --tenant ${{ secrets.tenant }}

      - name: Build the Nginx image and save it to the container registry
        run: cd ./containers/nginx-alpine &&
          az acr build
          --resource-group ppap-rg
          --registry ppapcr
          --file Dockerfile
          --image ppapcr/nginx-alpine:${{ github.sha }} .

      - name: Build the Flask image and save it to the container registry
        run: cd ./containers/uwsgi-server &&
          az acr build
          --resource-group ppap-rg
          --registry ppapcr
          --file Dockerfile
          --image ppapcr/uwsgi-server:${{ github.sha }} .

      - name: Build the Payment Stream Processor image and save it to the container registry
        run: cd ./containers/payment-stream-processor &&
          az acr build
          --resource-group ppap-rg
          --registry ppapcr
          --file Dockerfile
          --image ppapcr/payment-stream-processor:${{ github.sha }} .

      # Set the target AKS cluster.
      - uses: Azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          cluster-name: ppap-kube
          resource-group: ppap-rg

      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            kube-specs/ppap-deployment.yaml
            kube-specs/ppap-deployment-ppap-engine.yaml
            kube-specs/ppap-service.yaml
          images: |
            ppapcr.azurecr.io/ppapcr/uwsgi-server:${{ github.sha }}
            ppapcr.azurecr.io/ppapcr/nginx-alpine:${{ github.sha }}
            ppapcr.azurecr.io/ppapcr/payment-stream-processor:${{ github.sha }}
